### ISSUE TITLE
Not sure how else to do so...

### ISSUE THREAD

**Issue by shadowlightwolf89** [StevenThuriot/Marbles#3]
So I'll open an issue for clarification...

You say that you'd like people to ask before they use this theme, how are we to ask?

PS. this is me asking as well as asking about asking XD

**Comment by StevenThuriot** [comment]
Hi,

First of all, thanks for the interest! 

I _initially_ put the message there since at the time, the idea of everyone running the same template seemed kind of appalling. However, having thought it through, I guess it's quite alright as long as you keep my footer in there.

<sub>( PS: If you do use it, please fork the repo rather than copy pasting so the link gets maintained. Thanks :smile: )</sub>
